name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: govindhan1234 
          password: dckr_pat_PsCQzb2Xx2F7LpqTssEmaXVrG44

      - name: Build Docker image
        run: |
          docker build -t govindhan1234/github-actions-mini:latest .

      - name: Push Docker image
        run: |
          docker push govindhan1234/github-actions-mini:latest

      - name: Pull Docker image (test)
        run: |
          docker pull govindhan1234/github-actions-mini:latest

      - name: Run Docker container (test)
        run: |
          docker run -d -p 3000:3000 --name test-container govindhan1234/github-actions-mini:latest
          sleep 10
          docker ps
          docker logs test-container
